# Site settings
title: Code Craft Creep 
multisite_title: Ignacio Prado
email: ignacio@gatogordoweb.com 
description: > # this means to ignore newlines until "baseurl:"
  A technical learning blog.  Code walk-throughs, learning agendas, and selective implementation of advice from Dave Hoover's "Apprenticeship Patterns"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ignacioprado.net/blog" # the base hostname & protocol for your site
multisite_url: "http://ignacioprado.net"
twitter_username: i_prado78 
github_username: gato-gordo 

# Build settings
markdown: kramdown
