# Site settings
title: Code Craft Creep 
multisite_title: Ignacio Prado
email: ignacio@gatogordoweb.com 
description: "A technical learning blog.  Code walk-throughs, learning agendas,
and selective implementation of advice from Dave Hoover and Adewale Oshineye's
\"Apprenticeship Patterns\"."
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ignacioprado.net/blog" # the base hostname & protocol for your site
multisite_url: "http://ignacioprado.net"
twitter_username: ignacio_prado78 
github_username: gato-gordo
redcarpet:
  extensions: [tables]

# Build settings
markdown: kramdown
